# Generated by Django 5.0.6 on 2026-01-08 15:32

import apps.academy.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prodi',
            name='jurusan',
        ),
        migrations.RemoveField(
            model_name='prodi',
            name='kode_mk',
        ),
        migrations.RemoveField(
            model_name='prodi',
            name='nama_mk',
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('credit_t', models.PositiveIntegerField()),
                ('group', models.CharField(max_length=50)),
                ('credit_p', models.PositiveIntegerField()),
                ('duration_weeks', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academy.prodi')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academy.courseperiod')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('agenda_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_online', models.BooleanField(default=False)),
                ('meeting_url', models.URLField(blank=True, help_text='Link Zoom/GMeet')),
                ('learning_outcome', models.TextField(blank=True, null=True)),
                ('teaching_method', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='academy.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='academy.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('sick', 'Sick')], default='present', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academy.courseagenda')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academy.courseparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academy.course')),
            ],
            options={
                'verbose_name': 'Course Section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('video', 'Video'), ('reading', 'Reading/Article'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='video', max_length=20)),
                ('video_url', models.URLField(blank=True)),
                ('file_attachment', models.FileField(blank=True, upload_to='course/materials/')),
                ('text_content', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_preview', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academy.coursesection')),
            ],
            options={
                'verbose_name': 'Course Material',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentMaterialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='academy.coursematerial')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_progress', to='academy.courseparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='UserDosen',
            fields=[
                ('nip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('status_kepegawaian', models.CharField(blank=True, choices=[('PNS', 'PNS'), ('CPNS', 'CPNS'), ('PPPK', 'PPPK'), ('NON-ASN', 'NON-ASN')], max_length=15, null=True)),
                ('telp', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('nidn', models.CharField(blank=True, max_length=20, null=True)),
                ('pangkat', models.CharField(blank=True, choices=[('Penata Muda Tingkat I', 'Penata Muda Tingkat I'), ('Penata', 'Penata'), ('Penata Tingkat I', 'Penata Tingkat I'), ('Pembina', 'Pembina'), ('Pembina Utama Muda', 'Pembina Utama Muda'), ('Pembina Utama Madya', 'Pembina Utama Madya'), ('Pembina Utama', 'Pembina Utama')], max_length=30, null=True)),
                ('golongan', models.CharField(blank=True, choices=[('III/b', 'III/b'), ('III/c', 'III/c'), ('III/d', 'III/d'), ('IV/a', 'IV/a'), ('IV/b', 'IV/b'), ('IV/c', 'IV/c'), ('IV/d', 'IV/d'), ('IV/e', 'IV/e')], max_length=10, null=True)),
                ('jafung', models.CharField(blank=True, choices=[('Asisten Ahli', 'Asisten Ahli'), ('Lektor', 'Lektor'), ('Lektor Kepala', 'Lektor Kepala'), ('Guru Besar', 'Guru Besar')], max_length=15, null=True)),
                ('bidang_keahlian', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(upload_to=apps.academy.models.rename_photo_dsn)),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.prodi')),
            ],
        ),
        migrations.AddField(
            model_name='courseparticipant',
            name='mahasiswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_courses', to='academy.userdosen'),
        ),
        migrations.CreateModel(
            name='CourseAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='academy.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to='academy.userdosen')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='coached_courses', to='academy.userdosen'),
        ),
        migrations.CreateModel(
            name='UserMhs',
            fields=[
                ('nim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('telp', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('tgl_masuk', models.DateField(blank=True, null=True)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(upload_to=apps.academy.models.rename_photo_mhs)),
                ('penasehat_akademik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermhs_pa', to='academy.userdosen')),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermhs_prodi', to='academy.prodi')),
            ],
        ),
        migrations.CreateModel(
            name='UserProdi',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('telp', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('photo', models.ImageField(upload_to=apps.academy.models.rename_photo_admin)),
                ('prodi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.prodi')),
            ],
        ),
        migrations.DeleteModel(
            name='Jurusan',
        ),
    ]
