# Generated by Django 5.0.6 on 2026-01-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_courseperiod_remove_prodi_jurusan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseparticipant',
            name='mahasiswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_courses', to='academy.usermhs'),
        ),
    ]
