# Generated by Django 5.0.6 on 2026-01-09 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_courseparticipant_mahasiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academy.courseagenda'),
        ),
    ]
