# Generated by Django 5.0.6 on 2026-01-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_coursematerial_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseagenda',
            options={'ordering': ['agenda_date']},
        ),
        migrations.RenameField(
            model_name='coursematerial',
            old_name='section',
            new_name='agenda',
        ),
        migrations.AlterField(
            model_name='courseagenda',
            name='learning_outcome',
            field=models.TextField(blank=True, help_text='Capaian Pembelajaran', null=True),
        ),
        migrations.AlterField(
            model_name='courseagenda',
            name='teaching_method',
            field=models.CharField(blank=True, help_text='Metode Pengajaran', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CourseSection',
        ),
    ]
