# Generated by Django 5.0.6 on 2026-01-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_courseagenda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseagenda',
            name='agenda_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
