# Generated by Django 5.0.6 on 2026-01-09 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_courseagenda_agenda_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Instruksi pengerjaan tugas')),
                ('file_instruction', models.FileField(blank=True, null=True, upload_to='course/assignments/instructions/')),
                ('due_date', models.DateTimeField()),
                ('max_score', models.IntegerField(default=100)),
                ('allow_late_submission', models.BooleanField(default=False, help_text='Izinkan pengumpulan telat?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academy.courseagenda')),
            ],
            options={
                'verbose_name': 'Course Assignment',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='course/assignments/submissions/')),
                ('submitted_text', models.TextField(blank=True, help_text='Jawaban teks/link GDrive', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academy.courseassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academy.usermhs')),
            ],
        ),
    ]
