# Generated by Django 5.0.6 on 2026-01-09 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_courseassignment_studentassignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
