# Generated by Django 5.0.6 on 2026-01-11 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_course_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
