# Generated by Django 5.0.6 on 2026-01-11 13:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_coursematerial_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
