# Generated by Django 5.0.6 on 2026-01-11 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_remove_coursematerial_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
