# Generated by Django 5.0.6 on 2026-01-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_coursematerial_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='uuid',
        ),
    ]
