# Generated by Django 5.0.6 on 2026-01-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_remove_coursematerial_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentassignmentsubmission',
            name='submitted_file',
        ),
        migrations.AddField(
            model_name='studentassignmentsubmission',
            name='submitted_link',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
