# Generated by Django 5.0.6 on 2026-01-14 10:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_alter_coursematerial_material_type_coursequiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequiz',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizoption',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentquizanswer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentquizattempt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
