# Generated by Django 5.0.6 on 2026-01-15 01:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_alter_coursequiz_id_alter_quizoption_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='academy.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('leader', 'Ketua'), ('member', 'Anggota')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='academy.coursegroup')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='academy.courseparticipant')),
            ],
            options={
                'unique_together': {('group', 'participant')},
            },
        ),
    ]
