# Generated by Django 5.0.6 on 2026-01-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0019_chatroom_group_chatroom_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
