# Generated by Django 5.0.6 on 2026-01-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='assignment_type',
            field=models.CharField(choices=[('individual', 'Individu'), ('group', 'Kelompok')], default='individual', max_length=20),
        ),
    ]
