# Generated by Django 5.0.6 on 2026-01-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0021_courseassignment_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassignmentsubmission',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Menyimpan ID kelompok agar nilai & file terikat ke kelompok, bukan cuma individu', null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.coursegroup'),
        ),
    ]
