# Generated by Django 5.0.6 on 2026-01-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0022_studentassignmentsubmission_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequiz',
            name='quiz_type',
            field=models.CharField(choices=[('quiz', 'Kuis Harian'), ('ujian', 'Ujian'), ('remedial', 'Remedial')], default='quiz', max_length=20),
        ),
    ]
