# Generated by Django 5.0.6 on 2026-01-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0024_alter_coursequiz_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequiz',
            name='quiz_type',
            field=models.CharField(choices=[('quiz', 'Kuis Harian'), ('ujian', 'Ujian Semester')], default='quiz', max_length=20),
        ),
    ]
