# Generated by Django 5.0.6 on 2026-01-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0028_alter_coursequiz_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('video', 'Video'), ('reading', 'Reading/Article')], default='video', max_length=20),
        ),
    ]
