# Generated by Django 5.0.6 on 2026-01-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0029_alter_coursematerial_material_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursematerial',
            old_name='is_preview',
            new_name='is_published',
        ),
    ]
