# Generated by Django 5.0.6 on 2026-01-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0030_rename_is_preview_coursematerial_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
