# Generated by Django 5.0.6 on 2026-01-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0031_courseassignment_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link_rps',
            field=models.URLField(blank=True, null=True),
        ),
    ]
