# Generated by Django 5.0.6 on 2026-01-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0033_bookcategory_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
