# Generated by Django 5.0.6 on 2026-04-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0035_calendarevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='guests',
        ),
    ]
