# Generated by Django 5.0.6 on 2026-04-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0036_remove_calendarevent_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='label',
            field=models.CharField(choices=[('Campus', 'Campus'), ('Business', 'Business'), ('Personal', 'Personal'), ('Family', 'Family'), ('Holiday', 'Holiday'), ('Finance', 'Finance'), ('Self-Dev', 'Self-Dev'), ('Social', 'Social'), ('Health', 'Health'), ('Spiritual', 'Spiritual'), ('Lainnya', 'Lainnya')], default='Business', max_length=20),
        ),
    ]
