# Generated by Django 5.0.6 on 2026-04-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0037_alter_calendarevent_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='label',
            field=models.CharField(choices=[('Campus', 'Campus'), ('Business', 'Business'), ('Personal', 'Personal'), ('Family', 'Family'), ('Holiday', 'Holiday'), ('Finance', 'Finance'), ('Self-Dev', 'Self-Dev'), ('Health & Fitness', 'Health & Fitness'), ('Lainnya', 'Lainnya')], default='Campus', max_length=20),
        ),
    ]
