# Generated by Django 5.0.6 on 2026-04-12 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0038_alter_calendarevent_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseagenda',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Dosen yang membuat agenda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agendas', to='academy.userdosen'),
        ),
    ]
