# Generated by Django 5.0.6 on 2026-04-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0041_courseagenda_allow_discussion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseagenda',
            name='allow_discussion',
            field=models.BooleanField(default=True, help_text='Nonaktifkan threads.'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='allow_discussion',
            field=models.BooleanField(default=True, help_text='Nonaktifkan threads.'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='allow_discussion',
            field=models.BooleanField(default=True, help_text='Nonaktifkan threads.'),
        ),
    ]
