# Generated by Django 5.0.6 on 2026-04-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0043_discussion_opt_in_defaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursediscussion',
            name='body',
        ),
    ]
