# Generated by Django 5.0.6 on 2026-04-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0044_remove_coursediscussion_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursediscussion',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
