# Generated by Django 5.0.6 on 2026-04-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0045_coursediscussion_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursediscussion',
            name='body',
        ),
        migrations.AlterField(
            model_name='courseagenda',
            name='allow_discussion',
            field=models.BooleanField(default=False, help_text='Centang untuk menampilkan ke beranda diskusi.'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='allow_discussion',
            field=models.BooleanField(default=False, help_text='Centang untuk menampilkan ke beranda diskusi.'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='allow_discussion',
            field=models.BooleanField(default=False, help_text='Centang untuk menampilkan ke beranda diskusi.'),
        ),
    ]
