# Generated by Django 5.0.6 on 2026-05-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0046_remove_coursediscussion_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseagenda',
            options={'ordering': ['session_number', 'agenda_date']},
        ),
        migrations.AlterUniqueTogether(
            name='courseagenda',
            unique_together={('course', 'session_number')},
        ),
        migrations.AddField(
            model_name='courseagenda',
            name='session_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseagenda',
            name='agenda_date',
            field=models.DateTimeField(blank=True, help_text='Tanggal & jam pelaksanaan', null=True),
        ),
        migrations.AlterField(
            model_name='courseagenda',
            name='agenda_type',
            field=models.CharField(default='Perkuliahan', max_length=20),
        ),
        migrations.RemoveField(
            model_name='courseagenda',
            name='description',
        ),
    ]
