# Generated by Django 5.0.6 on 2026-05-06 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0047_alter_courseagenda_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration_weeks',
        ),
    ]
