# Generated by Django 5.0.6 on 2026-05-06 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0048_remove_course_duration_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseannouncement',
            name='allow_discussion',
            field=models.BooleanField(default=False, help_text='Centang untuk membuka thread diskusi di beranda kelas.'),
        ),
        migrations.AddField(
            model_name='coursediscussion',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='academy.courseannouncement'),
        ),
    ]
