# Generated by Django 5.0.6 on 2026-05-06 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0049_courseannouncement_allow_discussion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursediscussion',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='academy.courseannouncement'),
        ),
    ]
