# Generated by Django 5.0.6 on 2026-05-06 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0050_alter_coursediscussion_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursediscussion',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='academy.courseagenda'),
        ),
        migrations.AlterField(
            model_name='coursediscussion',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='academy.courseassignment'),
        ),
        migrations.AlterField(
            model_name='coursediscussion',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='academy.coursematerial'),
        ),
    ]
