# Generated by Django 5.0.6 on 2026-05-06 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0051_alter_coursediscussion_agenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseagenda',
            name='lecturer',
            field=models.ForeignKey(blank=True, help_text='Dosen pengampu sesi ini (bisa berbeda dari pembuat)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_agendas', to='academy.userdosen'),
        ),
    ]
