# Generated by Django 5.0.6 on 2026-05-06 11:28

import apps.academy.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0052_courseagenda_lecturer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nama Berkas')),
                ('file_type', models.CharField(choices=[('video_url', 'Video (URL YouTube/Vimeo)'), ('pdf', 'Dokumen PDF'), ('docx', 'Dokumen Word'), ('pptx', 'Presentasi PowerPoint'), ('image', 'Gambar'), ('other', 'Berkas Lainnya')], default='other', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.academy.models.media_library_upload_path)),
                ('video_url', models.URLField(blank=True, help_text='Isi jika tipe adalah Video URL (YouTube/Vimeo)', null=True)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='Ukuran file dalam bytes (diisi otomatis)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Library File',
                'verbose_name_plural': 'Media Library Files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='media_file',
            field=models.ForeignKey(blank=True, help_text='Pilih dari Media Library (akan diprioritaskan di atas file_attachment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_materials', to='academy.mediafile'),
        ),
    ]
