# Generated by Django 5.0.6 on 2026-05-06 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0053_mediafile_coursematerial_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='media_file',
        ),
        migrations.CreateModel(
            name='AgendaMediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='academy.courseagenda')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='academy.mediafile')),
            ],
            options={
                'verbose_name': 'Agenda Media Item',
                'ordering': ['order', 'created_at'],
                'unique_together': {('agenda', 'media_file')},
            },
        ),
    ]
