# Generated by Django 5.0.6 on 2026-05-07 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0054_remove_coursematerial_media_file_agendamediaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='duration_seconds',
        ),
    ]
