# Generated by Django 5.0.6 on 2026-05-07 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0055_remove_coursematerial_duration_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='file_attachment',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='coursematerial',
            name='video_url',
        ),
    ]
