# Generated by Django 5.0.6 on 2026-05-07 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0056_remove_coursematerial_file_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_materials', to='academy.userdosen', verbose_name='Dibuat oleh'),
        ),
    ]
