# Generated by Django 5.0.6 on 2026-05-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0057_coursematerial_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prodi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academy.prodi'),
        ),
    ]
