# Generated by Django 5.0.6 on 2026-05-08 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0058_alter_course_prodi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseannouncement',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='academy.course'),
            preserve_default=False,
        ),
    ]
