# Generated by Django 5.0.6 on 2026-05-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0059_alter_courseannouncement_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamediaitem',
            name='media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items', to='academy.mediafile'),
        ),
    ]
