# Generated by Django 5.0.6 on 2026-05-08 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0060_alter_agendamediaitem_media_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseassignment',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academy.courseagenda'),
        ),
        migrations.AlterField(
            model_name='coursediscussion',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='academy.courseagenda'),
        ),
        migrations.AlterField(
            model_name='coursediscussion',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='academy.courseannouncement'),
        ),
        migrations.AlterField(
            model_name='coursediscussion',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='academy.courseassignment'),
        ),
        migrations.AlterField(
            model_name='coursediscussion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursediscussion',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='academy.coursematerial'),
        ),
        migrations.AlterField(
            model_name='coursediscussionreply',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursediscussionreply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='academy.coursediscussionreply'),
        ),
        migrations.AlterField(
            model_name='coursequiz',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='academy.course'),
        ),
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='academy.courseassignment'),
        ),
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Menyimpan ID kelompok agar nilai & file terikat ke kelompok, bukan cuma individu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.coursegroup'),
        ),
        migrations.AlterField(
            model_name='studentassignmentsubmission',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='academy.usermhs'),
        ),
        migrations.AlterField(
            model_name='studentquizanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.quizquestion'),
        ),
        migrations.AlterField(
            model_name='studentquizattempt',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to='academy.courseparticipant'),
        ),
        migrations.AlterField(
            model_name='studentquizattempt',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='academy.coursequiz'),
        ),
    ]
