# Generated by Django 5.0.6 on 2026-05-08 15:54

import apps.academy.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0061_alter_courseassignment_agenda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('project', 'Project'), ('presentation', 'Presentation'), ('competition', 'Competition'), ('internship', 'Internship'), ('research', 'Research'), ('publication', 'Publication'), ('certificate', 'Certificate'), ('other', 'Other')], default='project', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True, help_text='Deskripsi singkat project')),
                ('body', models.TextField(blank=True, help_text='Penjelasan lengkap project')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.academy.models.portfolio_thumbnail_upload)),
                ('project_url', models.URLField(blank=True, help_text='Link project / presentasi / github / gdrive / youtube', max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='academy.categoryportfolio')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_projects', to='academy.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Portfolio',
                'verbose_name_plural': 'Student Portfolios',
                'ordering': ['-created_at'],
            },
        ),
    ]
