# Generated by Django 5.0.6 on 2026-05-09 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0062_categoryportfolio_studentportfolio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentportfolio',
            name='verification_note',
            field=models.TextField(blank=True, verbose_name='Catatan Verifikasi'),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak')], default='pending', max_length=10, verbose_name='Status Verifikasi'),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Verifikasi'),
        ),
        migrations.AddField(
            model_name='studentportfolio',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_portfolios', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi oleh'),
        ),
    ]
