# Generated by Django 5.0.6 on 2026-05-09 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0063_studentportfolio_verification_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentportfolio',
            name='verification_note',
        ),
    ]
