# Generated by Django 5.0.6 on 2026-05-09 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0064_remove_studentportfolio_verification_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentportfolio',
            name='like_count',
        ),
    ]
