# Generated by Django 5.0.6 on 2026-05-09 05:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0065_remove_studentportfolio_like_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kanban Board',
                'verbose_name_plural': 'Kanban Boards',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KanbanTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('label_color', models.CharField(blank=True, default='bg-label-primary', max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='kanban_attachments/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='academy.kanbanboard')),
            ],
            options={
                'verbose_name': 'Kanban Task',
                'verbose_name_plural': 'Kanban Tasks',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
