# Generated by Django 5.0.6 on 2026-05-09 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0066_kanbanboard_kanbantask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbantask',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_kanban_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan kepada'),
        ),
    ]
