# Generated by Django 5.0.6 on 2026-05-10 02:44

import apps.academy.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0069_kanbantask_creator_alter_kanbantask_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDocumentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('body', models.TextField(blank=True, help_text='Penjelasan lengkap panduan')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.academy.models.doc_thumbnail_upload)),
                ('video_url', models.URLField(blank=True, help_text='Link embed video panduan', max_length=500, null=True)),
                ('target_audience', models.CharField(choices=[('all', 'Semua Pengguna'), ('dosen', 'Dosen'), ('mahasiswa', 'Mahasiswa'), ('admin', 'Admin')], default='all', help_text='Panduan ditujukan untuk siapa?', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Documentation',
                'verbose_name_plural': 'App Documentations',
                'ordering': ['-created_at'],
            },
        ),
    ]
