# Generated by Django 5.0.6 on 2026-05-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0070_appdocumentation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Chat Room', 'verbose_name_plural': 'Chat Rooms'},
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='is_graded',
            field=models.BooleanField(default=False, help_text='Tandai jika sudah diperiksa oleh dosen'),
        ),
    ]
