# Generated by Django 5.0.6 on 2026-08-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0071_alter_chatroom_options_studentquizattempt_is_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseagenda',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
