# Generated by Django 5.0.6 on 2026-08-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0072_courseagenda_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizattempt',
            name='security_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='security_violation_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
