# Generated by Django 5.0.6 on 2026-08-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0073_studentquizattempt_security_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequiz',
            name='max_security_violations',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
