# Generated by Django 5.0.6 on 2026-10-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0074_coursequiz_max_security_violations'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseagenda',
            name='documentation_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
